CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102193214_AddMemberDetailsColumnsToAccountMaster') THEN
    ALTER TABLE accountmaster ADD relativename text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102193214_AddMemberDetailsColumnsToAccountMaster') THEN
    ALTER TABLE accountmaster ADD gender integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102193214_AddMemberDetailsColumnsToAccountMaster') THEN
    ALTER TABLE accountmaster ADD phoneno1 text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102193214_AddMemberDetailsColumnsToAccountMaster') THEN
    ALTER TABLE accountmaster ADD email text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102193214_AddMemberDetailsColumnsToAccountMaster') THEN
    ALTER TABLE accountmaster ADD addressline text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102193214_AddMemberDetailsColumnsToAccountMaster') THEN
    ALTER TABLE accountmaster ADD dob timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102193214_AddMemberDetailsColumnsToAccountMaster') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251102193214_AddMemberDetailsColumnsToAccountMaster', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    ALTER TABLE jointaccountinfo ADD jointaccholderaccountnumber text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    ALTER TABLE accountmaster ADD addedusing text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE accountkistdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        accountid integer NOT NULL,
        loanamountpassed double precision,
        loanperiod integer,
        slabid integer,
        standardinterestrate double precision,
        overdueinterestrate double precision,
        loandate timestamp without time zone NOT NULL,
        kistinterval integer,
        kistfirstdate timestamp without time zone NOT NULL,
        kistamount double precision,
        kistprinpart double precision,
        kistintpart double precision,
        loanno character varying(20),
        kistwithinterest character varying(2),
        status character varying(2),
        loanperiodindays integer,
        kistintervalindays integer,
        kislintamt double precision,
        marginmoney double precision,
        CONSTRAINT pk_accountkistdetail PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE accountkistschedule (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        loanaccid integer,
        kistnumber integer,
        date timestamp without time zone,
        kistamount numeric(24,2),
        principalamt numeric(24,2),
        interestamt numeric(24,2),
        CONSTRAINT pk_accountkistschedule PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE accountlimitdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        accountid integer NOT NULL,
        loanno character varying(20) NOT NULL,
        loandate timestamp without time zone NOT NULL,
        loanamountpassed double precision NOT NULL,
        loanlimitperiodinmonths integer NOT NULL,
        loanlimitperiodindays integer NOT NULL,
        slabid integer NOT NULL,
        standardinterestrate double precision NOT NULL,
        overdueinterestrate double precision NOT NULL,
        CONSTRAINT pk_accountlimitdetail PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE branchsession (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        sessionfrom integer NOT NULL,
        sessionto integer NOT NULL,
        fromdate timestamp without time zone NOT NULL,
        todate timestamp without time zone NOT NULL,
        iscurrent boolean NOT NULL,
        isfirst boolean NOT NULL,
        CONSTRAINT branchsession_pkey PRIMARY KEY (id, branchid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE fdaccountdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        accountid integer NOT NULL,
        fdamount numeric(18,2) NOT NULL,
        fddate timestamp without time zone NOT NULL,
        fdmaturitydate timestamp without time zone NOT NULL,
        maturityamount numeric(18,2) NOT NULL,
        ltdno integer NOT NULL,
        fdstatus integer NOT NULL,
        fdperiodmonths integer NOT NULL,
        fdperioddays integer NOT NULL,
        slabid integer NOT NULL,
        intrate numeric(18,4) NOT NULL,
        intcompinterval integer NOT NULL,
        serialno integer NOT NULL,
        voucherdate timestamp without time zone NOT NULL,
        interestpaidinterval integer,
        interestpaidamount numeric(18,2),
        misaccid integer,
        CONSTRAINT fdaccountdetail_pkey PRIMARY KEY (id, branchid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE fdinterestslab (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        slabname text NOT NULL,
        fdproductid integer NOT NULL,
        fromdays integer NOT NULL,
        todays integer NOT NULL,
        compoundinginterval integer NOT NULL,
        CONSTRAINT fdinterestslab_pkey PRIMARY KEY (id, branchid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE fdinterestslabdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        fdintslabinfoid integer NOT NULL,
        fdintslabid integer NOT NULL,
        agefrom numeric NOT NULL,
        ageto numeric NOT NULL,
        interestrate numeric NOT NULL,
        CONSTRAINT fdinterestslabdetail_pkey PRIMARY KEY (id, branchid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE fdinterestslabinfo (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        fdproductid integer NOT NULL,
        applicabledate timestamp without time zone NOT NULL,
        CONSTRAINT fdinterestslabinfo_pkey PRIMARY KEY (id, branchid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanaccfdpledge (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        loanaccid integer,
        fdaccid integer,
        fdaccdetid integer,
        lateststatus integer,
        date timestamp without time zone,
        CONSTRAINT pk_loanaccfdpledge PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanaccfdpledgedetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        laccfdpledgeid integer,
        date timestamp without time zone,
        status integer,
        CONSTRAINT pk_loanaccfdpledgedetail PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanaccopeningbalance (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        accid integer,
        totalbalance numeric(24,2),
        baltype character varying(2),
        overduebal numeric(24,0),
        overbaltype character varying(2),
        openint numeric(24,0),
        openinttype character varying(2),
        openoverint numeric(24,0),
        openoverinttype character varying(2),
        headcode bigint,
        overduedate timestamp without time zone,
        CONSTRAINT pk_loanaccopeningbalance PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanaccountbalancedetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        loanopenbalid integer NOT NULL,
        accountid integer NOT NULL,
        amountdr numeric(24,2) NOT NULL,
        amountcr numeric(24,2) NOT NULL,
        intdr numeric(24,2) NOT NULL,
        intcr numeric(24,2) NOT NULL,
        date timestamp without time zone NOT NULL,
        valuedate timestamp without time zone NOT NULL,
        status character varying(5),
        headcode bigint,
        CONSTRAINT pk_loanaccountbalancedetail PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanaccountrecoveryinterest (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        baldetailid integer NOT NULL,
        intcategoryid integer NOT NULL,
        amountdr numeric(24,2) NOT NULL,
        amountcr numeric(24,2) NOT NULL,
        accid integer NOT NULL,
        entrydate timestamp without time zone,
        valuedate timestamp without time zone,
        CONSTRAINT pk_loanaccountrecoveryinterest PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanaccrdpledge (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        loanaccid integer,
        rdaccid integer,
        rdaccdetid integer,
        lateststatus integer,
        date timestamp without time zone,
        CONSTRAINT pk_loanaccrdpledge PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanaccrdpledgedetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        laccrdpledgeid integer,
        date timestamp without time zone,
        status integer,
        ishoupdated smallint,
        CONSTRAINT pk_loanaccrdpledgedetail PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanguarwitness (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        loanaccid integer,
        date timestamp without time zone,
        guar1memid integer,
        guar1membrid integer NOT NULL,
        guar2memid integer,
        guar2membrid integer NOT NULL,
        witness1memid integer,
        wit1membrid integer,
        witness2memid integer,
        wit2membrid integer NOT NULL,
        CONSTRAINT pk_loanguarwitness PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanproduct (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        code character varying(3) NOT NULL,
        productname character varying(50) NOT NULL,
        namesl character varying(75),
        effectivefrom timestamp without time zone NOT NULL,
        CONSTRAINT loanproduct_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanproductadvancement (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        productid integer NOT NULL,
        disbursmentmode character varying(50) NOT NULL,
        maxnoofdisbursments integer NOT NULL,
        minloanamount numeric(24,2) NOT NULL,
        maxloanamount numeric(24,2) NOT NULL,
        issharemoneyreq character varying(2) NOT NULL,
        loanperiodtype character varying(2),
        overdraftlimit smallint NOT NULL,
        loanamtperonsecurityrd numeric(24,2),
        loanamtperonsecurityfd numeric(24,2),
        CONSTRAINT loanproductadvancement_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanproductbranchwiserule (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        loanproductid integer NOT NULL,
        mclplanid integer,
        npaplanid integer,
        legalplanid integer,
        operatedby character varying(2),
        accnoornamefirst character varying(2),
        temprecaccid integer,
        currentrecoverableintacc integer,
        intincomeacc integer,
        overduerecoverableintacc integer,
        isapplyoverint smallint NOT NULL,
        ovrintprovacc integer NOT NULL,
        intwrtdepositpledge integer,
        ovrintfromopendate smallint NOT NULL,
        actonexpposting integer,
        CONSTRAINT loanproductbranchwiserule_pkey PRIMARY KEY (id, branchid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanproductdefinition (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        productid integer NOT NULL,
        typeid integer NOT NULL,
        categoryid integer,
        securityids character varying(50) NOT NULL,
        secreviewfreqperiod integer NOT NULL,
        docplanid integer,
        intschedule integer,
        intformulae integer,
        actonintposting integer,
        CONSTRAINT loanproductdefinition_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanproductmarginmoneyrule (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        advid integer NOT NULL,
        ratioorperc integer NOT NULL,
        loanproportion double precision NOT NULL,
        marginproportion double precision NOT NULL,
        mmpercentage double precision NOT NULL,
        CONSTRAINT loanproductmarginmoneyrule_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanproductposting (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        productid integer NOT NULL,
        principalbalheadcode bigint NOT NULL,
        miscincheadcode bigint NOT NULL,
        minballeftlimitheadcode bigint NOT NULL,
        minbalgivenlimitheadcode bigint NOT NULL,
        expheadcode bigint NOT NULL,
        recoverableintheadcode bigint,
        CONSTRAINT loanproductposting_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanproductrecovery (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        productid integer NOT NULL,
        recoverymode character varying(50) NOT NULL,
        recoveryseq character varying(50) NOT NULL,
        minballeftlimit double precision NOT NULL,
        minbalgivenlimit double precision NOT NULL,
        applyovrinton character varying(5),
        intrecoveredinadvance smallint,
        intpostinginterval integer,
        stdoverdueonkistdate smallint,
        recoveryadjustmentseq integer NOT NULL,
        CONSTRAINT loanproductrecovery_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanslab (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        name character varying(50) NOT NULL,
        namesl character varying(50),
        date timestamp without time zone NOT NULL,
        loanproductid integer NOT NULL,
        CONSTRAINT pk_loanslab PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE loanslabdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        slabid integer NOT NULL,
        fromamount numeric NOT NULL,
        toamount numeric NOT NULL,
        periodfrom integer,
        periodto integer,
        periodfromindays integer,
        periodtoindays integer,
        stdintrate double precision,
        penalintrate double precision,
        CONSTRAINT pk_loanslabdetail PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE rdaccountdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        accid integer,
        rdnumber integer,
        rddate timestamp without time zone NOT NULL,
        rdamount numeric NOT NULL,
        noofmonths integer,
        rdslabid integer,
        interestrate double precision,
        maturitydate timestamp without time zone,
        kistamt numeric,
        kistinterval integer,
        firstkistdate timestamp without time zone,
        penaltyamt numeric,
        status integer,
        maturityamt numeric,
        noofdays integer,
        compoundinginterval integer,
        maturedon timestamp without time zone,
        prematuredon timestamp without time zone,
        CONSTRAINT rdaccountdetail_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE rdinterestslab (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        slabname text NOT NULL,
        rdproductid integer NOT NULL,
        applicabledate timestamp without time zone NOT NULL,
        CONSTRAINT rdinterestslab_pkey PRIMARY KEY (id, branchid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE rdinterestslabdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        rdintslabid integer NOT NULL,
        slabno integer NOT NULL,
        fromamount numeric NOT NULL,
        toamount numeric NOT NULL,
        kistinterval character varying(20) NOT NULL,
        periodfrom integer NOT NULL,
        periodto integer NOT NULL,
        interestrate numeric NOT NULL,
        CONSTRAINT rdinterestslabdetail_pkey PRIMARY KEY (id, branchid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE rdproduct (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        productname character varying(255) NOT NULL,
        productnamesl character varying(255) NOT NULL,
        productcode character varying(10) NOT NULL,
        effectivefrom timestamp without time zone NOT NULL,
        CONSTRAINT rdproduct_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE rdproductbranchwiserule (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        rdproductid integer NOT NULL,
        intformula integer NOT NULL,
        accnogeneration character varying(2),
        printcertificate smallint,
        intexpaccid integer,
        penaltyincaccid integer,
        closingchargesacc integer,
        kistaftermaturity smallint,
        paymentdatetype smallint,
        noofdayormonth integer,
        CONSTRAINT rdproductbranchwiserule_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE rdproductdefinition (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        rdproductid integer,
        docplanid integer,
        minperiodlimitmonths integer,
        maxperiodlimitmonths integer,
        CONSTRAINT rdproductdefinition_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE rdproductinterestrules (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        productid integer,
        date timestamp without time zone,
        intratefrom double precision,
        intrateto double precision,
        intvariationforaccless double precision,
        intvariationforaccexceed double precision,
        intpostinginterval integer,
        intcompoundinginterval integer,
        actonintposting integer,
        intrateonpremat double precision,
        postmaturityintrate double precision,
        minlockinperioddays integer,
        CONSTRAINT rdproductinterestrules_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE rdproductposting (
        id integer GENERATED ALWAYS AS IDENTITY,
        brid integer NOT NULL,
        rdproductid integer,
        principalbalheadcode bigint,
        intpayableheadcode bigint,
        CONSTRAINT rdproductposting_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE refreshtoken (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        token text NOT NULL,
        userid integer NOT NULL,
        branchid integer NOT NULL,
        claimssnapshot text NOT NULL,
        expiresat timestamp without time zone NOT NULL,
        isrevoked boolean NOT NULL,
        createdat timestamp without time zone NOT NULL,
        replacedbytoken text,
        CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE voucherfddetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        voucherid integer NOT NULL,
        vacccrdrid integer NOT NULL,
        fdaccid integer NOT NULL,
        fdaccdetid integer NOT NULL,
        amountcr numeric(18,2) NOT NULL,
        amountdr numeric(18,2) NOT NULL,
        operation character varying(5) NOT NULL,
        valuedate timestamp without time zone,
        voucherdate timestamp without time zone,
        intdr numeric(18,2),
        intcr numeric(18,2),
        vouchermainstatus character varying(2),
        CONSTRAINT voucherfddetail_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE voucherrddetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        vacccrdrid integer NOT NULL,
        rdaccid integer NOT NULL,
        rdaccdetid integer NOT NULL,
        amountcr double precision NOT NULL,
        amountdr double precision NOT NULL,
        operation text NOT NULL,
        valuedate timestamp without time zone,
        voucherdate timestamp without time zone,
        othrefaccid integer,
        penalamt numeric,
        penalaccid integer,
        intdr double precision,
        intcr double precision,
        vouchermainstatus text,
        voucherid integer NOT NULL,
        CONSTRAINT voucherrddetail_pkey PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE TABLE vouchersavingdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        vacccrdrid integer NOT NULL,
        operation character varying(3),
        accid integer,
        amt numeric,
        chequebookid integer,
        chequeno integer,
        valuedate timestamp without time zone NOT NULL,
        voucherdate timestamp without time zone NOT NULL,
        vouchermainstatus character varying(2) NOT NULL,
        voucherid integer NOT NULL,
        CONSTRAINT pk_vouchersavingdetail PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE UNIQUE INDEX ix_branchsession_id_branchid ON branchsession (id, branchid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE UNIQUE INDEX ix_fdaccountdetail_id_branchid ON fdaccountdetail (id, branchid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    CREATE UNIQUE INDEX ix_voucherfddetail_id_brid ON voucherfddetail (id, brid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260425134135_AddRefreshToken') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260425134135_AddRefreshToken', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516152017_AddIntCalcMethodToLoanProductDefinition') THEN
    ALTER TABLE loanproductdefinition ADD intcalcmethod character varying(12);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516152017_AddIntCalcMethodToLoanProductDefinition') THEN
    CREATE TABLE auditlog (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        branchid integer NOT NULL,
        userid text NOT NULL,
        username text NOT NULL,
        action text NOT NULL,
        module text NOT NULL,
        entityname text NOT NULL,
        entityid text,
        oldvalue text,
        newvalue text,
        ipaddress text,
        workingdate text,
        createdat timestamp without time zone NOT NULL,
        CONSTRAINT pk_auditlog PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516152017_AddIntCalcMethodToLoanProductDefinition') THEN
    CREATE TABLE voucherrecintdetail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        brid integer NOT NULL,
        vacccrdrid integer NOT NULL,
        voucherid integer NOT NULL,
        voucherno integer NOT NULL,
        entrydate timestamp without time zone NOT NULL,
        valuedate timestamp without time zone NOT NULL,
        intcatid integer NOT NULL,
        pamt double precision,
        accid integer NOT NULL,
        intdr double precision NOT NULL,
        intcr double precision NOT NULL,
        vouchermainstatus character varying(2),
        CONSTRAINT pk_voucherrecintdetail PRIMARY KEY (id, brid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260516152017_AddIntCalcMethodToLoanProductDefinition') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260516152017_AddIntCalcMethodToLoanProductDefinition', '8.0.8');
    END IF;
END $EF$;
COMMIT;

